language: node_js

node_js:
  - 10

sudo: false

services:
  - docker

script:
  - yarn build
  - docker build -t piggy1/portal .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
