language: node_js

node_js:
  - 10

sudo: false

services:
  - docker

script:
  - yarn build
  - docker build -t piggy1/portal .
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push piggy1/portal
