language:
  node_js

node_js:
 - 10
  
sudo:
  false
  
cache:
  directories:
    - $HOME/.m2

install:
  skip

services:
  - docker

script:
 - npm install
 - npm run build
 - docker build -t piggy1/portal .
 - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
 - docker push piggy1/portal
