language: node_js

node_js:
  - 10

sudo: false

cache:
  directories:
  - "$HOME/.sonar/cache"
  - "$HOME/google-cloud-sdk"

services:
  - docker

before_install:
- openssl aes-256-cbc -k "$DECRYPT_KEY" -in secret-storage.json.enc -out secret-storage.json -d -md sha256
- openssl aes-256-cbc -k "$DECRYPT_KEY" -in kub-deploy.json.enc -out kub-deploy.json -d -md sha256

script:
  - if [ $TRAVIS_BRANCH != "master" ]; then REACT_APP_ENV=dev CI=false yarn build; fi
  - if [ $TRAVIS_BRANCH != "master" ]; then docker build -t piggy1/portal .; fi
  - if [ $TRAVIS_BRANCH != "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ $TRAVIS_BRANCH != "master" ]; then docker push piggy1/portal; fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then REACT_APP_ENV=prod CI=false yarn build; fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then cat secret-storage.json | docker login -u _json_key --password-stdin https://gcr.io; fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then chmod 777 deploy_shell_canary.sh; fi
  - if [ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ./deploy_shell_canary.sh; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then chmod 777 deploy_shell_prod.sh; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ./deploy_shell_prod.sh; fi

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1