# To create a production ready build for react js web application and also 
# create corresponding docker image in Dockerhub

image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - npm install
          - npm test
          - npm run build
		  - npm config set piggyback-portal:username $DOCKER_USERNAME
		  - npm config set piggyback-portal:password $DOCKER_PASSWORD
		  - npm run docker-login
          - npm run docker-build
          - npm run docker-push
