apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-portal-canary
  namespace: production
spec:
  replicas: 0
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-portal
        env: canary
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-portal:v7
        name: piggyback-prod-runner-portal
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-portal
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
status: {}
