apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-portal-production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-portal
    spec:
      containers:
      - image: gcr.io/clear-variety-253514/piggy1-portal:v7
        name: piggyback-prod-runner-portal
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-portal
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
status: {}
